# Generated by Django 5.1.4 on 2025-06-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='name_rus',
        ),
        migrations.RenameField(
            model_name='category_of_food',
            old_name='name_ru',
            new_name='name_rus',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name_ru',
            new_name='name_rus',
        ),
    ]
