# Generated by Django 5.1.4 on 2025-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_name_ru_category_name_rus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_rus',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='category_of_food',
            old_name='name_rus',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name_rus',
            new_name='name_ru',
        ),
    ]
