# Generated by Django 5.1.4 on 2025-06-19 10:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image')),
                ('urls_of_add', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_tk', models.CharField(max_length=100)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_tk', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to='static/images')),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imgae_of_Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image')),
            ],
        ),
        migrations.CreateModel(
            name='Category_of_roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_tk', models.CharField(max_length=150)),
                ('rolls', models.ManyToManyField(related_name='rolls', to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_tk', models.CharField(max_length=150)),
                ('foods', models.ManyToManyField(related_name='foods', to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adress', models.CharField(max_length=300)),
                ('list_of_foods', models.ManyToManyField(related_name='list_of_foods', to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_tk', models.CharField(max_length=150)),
                ('category_of_roll', models.ManyToManyField(related_name='category_of_roll', to='menu.category_of_roll')),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_stories', models.ManyToManyField(related_name='image_of_stories', to='menu.imgae_of_stories')),
            ],
        ),
    ]
