# Generated by Django 5.1.4 on 2025-06-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_tk',
            new_name='name_tm',
        ),
        migrations.RenameField(
            model_name='category_of_roll',
            old_name='name_tk',
            new_name='name_tm',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='description_tk',
            new_name='description_tm',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name_tk',
            new_name='name_tm',
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='name_tk',
            new_name='name_tm',
        ),
    ]
