# Generated by Django 5.1.4 on 2025-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_name_tk_category_name_tm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
