# Generated by Django 5.1.4 on 2025-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_order_cart_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='static/image'),
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveBigIntegerField()),
                ('phone_number', models.CharField(max_length=100)),
                ('reservation_time', models.TimeField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('table_number', 'reservation_time')},
            },
        ),
    ]
