# Generated by Django 5.1.4 on 2025-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_food_image_tablereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_time',
            field=models.CharField(max_length=150),
        ),
    ]
