# Generated by Django 5.1.4 on 2025-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_tablereservation_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_time',
            field=models.DateTimeField(),
        ),
    ]
