# Generated by Django 5.1.4 on 2025-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_tablereservation_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('list_of_food', models.ManyToManyField(related_name='list_of_food', to='menu.food')),
            ],
        ),
    ]
