# Generated by Django 5.1.4 on 2025-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_creat_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveBigIntegerField()),
                ('list_of_foods', models.ManyToManyField(related_name='food_list', to='menu.food')),
            ],
        ),
    ]
