# Generated by Django 5.1.4 on 2025-06-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_table_creat_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableReservation',
        ),
    ]
