# Generated by Django 5.1.4 on 2025-06-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_delete_tablereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_creat_order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
