# Generated by Django 5.1.4 on 2025-06-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
