# Generated by Django 5.1.4 on 2025-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_delete_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='image_of_stories',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Катигория Блюда', 'verbose_name_plural': 'Катигория Блюд'},
        ),
        migrations.AlterModelOptions(
            name='category_of_roll',
            options={'verbose_name': 'Ролл', 'verbose_name_plural': 'Роллы'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюда', 'verbose_name_plural': 'Блюды'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ на самовынос', 'verbose_name_plural': 'Заказ на самовынос'},
        ),
        migrations.AlterModelOptions(
            name='order_cart',
            options={'verbose_name': 'Заказ на вынос', 'verbose_name_plural': 'Заказ на вынос'},
        ),
        migrations.AlterModelOptions(
            name='table_creat_order',
            options={'verbose_name': 'Заказ на столик', 'verbose_name_plural': 'Заказ на столик'},
        ),
        migrations.AddField(
            model_name='stories',
            name='image',
            field=models.ImageField(default='static/image/1.jpg', upload_to='static/image', verbose_name='Фотография для кружка'),
        ),
        migrations.AddField(
            model_name='stories',
            name='image2',
            field=models.ImageField(default='static/image/1.jpg', upload_to='static/image', verbose_name='Фотография после кружка'),
        ),
        migrations.AddField(
            model_name='stories',
            name='name_en',
            field=models.CharField(default='ru', max_length=150, verbose_name='Название на Английском'),
        ),
        migrations.AddField(
            model_name='stories',
            name='name_ru',
            field=models.CharField(default='ru', max_length=150, verbose_name='Название на русском'),
        ),
        migrations.AddField(
            model_name='stories',
            name='name_tk',
            field=models.CharField(default='ru', max_length=150, verbose_name='Название на Туркменском'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='static/image', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='urls_of_add',
            field=models.URLField(max_length=300, verbose_name='Ссылка на рекламу'),
        ),
        migrations.AlterField(
            model_name='category',
            name='foods',
            field=models.ManyToManyField(related_name='foods', to='menu.food', verbose_name='Вьбирете блюда которые будут относитья к этому категорию'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='image/1.jpg', upload_to='static/image', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, verbose_name='Название на Английском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tk',
            field=models.CharField(max_length=150, verbose_name='Название на Туркменском'),
        ),
        migrations.AlterField(
            model_name='category_of_roll',
            name='name_en',
            field=models.CharField(max_length=150, verbose_name='Название на Английском'),
        ),
        migrations.AlterField(
            model_name='category_of_roll',
            name='name_ru',
            field=models.CharField(max_length=150, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='category_of_roll',
            name='name_tk',
            field=models.CharField(max_length=150, verbose_name='Название на Туркменском'),
        ),
        migrations.AlterField(
            model_name='category_of_roll',
            name='rolls',
            field=models.ManyToManyField(related_name='rolls', to='menu.food', verbose_name='Вьбирете роллы которые будут относитья к этому категорию'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_en',
            field=models.TextField(verbose_name='Описание на Аглийском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_ru',
            field=models.TextField(verbose_name='Описание на русском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_tk',
            field=models.TextField(verbose_name='Описание на Туркменскком'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='static/image', verbose_name='Фотография блюда'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Название на Анлийком'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_tk',
            field=models.CharField(max_length=100, verbose_name='Название на Туркменском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена блюда'),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Порция или количиство'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Его вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='list_of_food',
            field=models.ManyToManyField(related_name='list_of_food', through='menu.OrderItem', to='menu.food', verbose_name='Список блюд заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Телефоный номер'),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='list_of_foods',
            field=models.ManyToManyField(related_name='list_of_foods', through='menu.Order_CartItem', to='menu.food', verbose_name='Список блюд заказа'),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Телефоный номер'),
        ),
        migrations.AlterField(
            model_name='table_creat_order',
            name='list_of_foods',
            field=models.ManyToManyField(related_name='food_list', through='menu.TableOrderItem', to='menu.food', verbose_name='Список блюд заказа'),
        ),
        migrations.AlterField(
            model_name='table_creat_order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефоный номер'),
        ),
        migrations.AlterField(
            model_name='table_creat_order',
            name='table_number',
            field=models.PositiveBigIntegerField(verbose_name='Намер столика'),
        ),
        migrations.DeleteModel(
            name='Imgae_of_Stories',
        ),
    ]
