# Generated by Django 5.2.1 on 2025-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_stories_image_of_stories_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюда', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Сторис', 'verbose_name_plural': 'Сторисы'},
        ),
        migrations.AlterField(
            model_name='stories',
            name='image2',
            field=models.ImageField(default='static/image/1.jpg', upload_to='static/image', verbose_name='Фотография истории'),
        ),
    ]
