# Generated by Django 5.2.1 on 2025-07-09 07:10

import menu.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_food_options_rename_image2_stories_circle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=menu.models.SVGImageField(upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=menu.models.SVGImageField(default='image/1.jpg', upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=menu.models.SVGImageField(upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=menu.models.SVGImageField(default='static/image/1.jpg', upload_to='static/image'),
        ),
    ]
